<template>
    <i-layout>
        <BaseHeader></BaseHeader>
        <i-layout-content>
            <slot></slot>
        </i-layout-content>
        <BaseFooter></BaseFooter>
    </i-layout>
</template>